export enum queryKeys {
  WALLET_BALANCE = "WALLET_BALANCE",
  ALL_BENEFICIARIES = "ALL_BENEFICIARIES",

  ALL_PRODUCTS = "ALL_PRODUCTS",
  ONGOING_ORDERS = "ONGOING_ORDERS",
  CART = "CART",

  BANKS = "BANKS",
  RESOLVE_ACCOUNT = "RESOLVE_ACCOUNT",
}
